### ISSUE TITLE
[Feature Request] Mermaid Support

### ISSUE THREAD

**Issue by taraxacum45e9a** [a2396837/hexo-theme-blank#2]
Mermaid is a tool that generates diagrams and charts, from markdown-inspired text definitions

Patch has been ready [here](https://github.com/LuminousXLB/hexo-theme-blank/commit/420945b4cf1ef3362a12e3fede71582fd81a4838), but I didn't create a pull request because of git conflicts.

**Comment by dewjohn** [comment]
Okay, I will deal with it later.

**Comment by dewjohn** [comment]
The version you are using is too low, there are many bugs, I hope you can re-git clone the new version.
