### ISSUE TITLE
没有阅读全文按钮

### ISSUE THREAD

**Issue by happy2h** [a2396837/hexo-theme-blank#3]
![image](https://user-images.githubusercontent.com/29790236/119627174-86939200-be3e-11eb-9e8a-d910f6d42e66.png)
作者这个是怎么回事

**Comment by happy2h** [comment]
这里需要在post的正文前面加上才有阅读全文

**Comment by dewjohn** [comment]
https://dmx.pub/posts/73f92298.html#%E6%96%87%E7%AB%A0%E8%87%AA%E5%8A%A8%E6%91%98%E8%A6%81

看下文档的“文章自动摘要”

(推荐）使用  标记精确截取文章部分作为摘要。

在文章 Front-matter 写 description

在文章 Front-matter 写 auto_excerpt: true 即可显示 length: 350 个字的摘要
