### ISSUE TITLE
示例网站是挂了嘛

### ISSUE THREAD

**Issue by L0ading-x** [a2396837/hexo-theme-blank#5]
示例网站是挂了嘛

**Comment by dewjohn** [comment]
> 示例网站是挂了嘛

域名过期了，最近忙着期末，这个寒假我会更新优化下主题，敬请期待吧！

**Comment by L0ading-x** [comment]
感谢回复，有讨论群什么的嘛，期待优化后的主题

**Comment by dewjohn** [comment]
> 感谢回复，有讨论群什么的嘛，期待优化后的主题

暂时没有这个想法哈，如果你想开发hexo主题什么的可以和我讨论一下
