### ISSUE TITLE
dmx.pub打不开了，想看具体的配置使用

### ISSUE THREAD

**Issue by HiNinoJay** [a2396837/hexo-theme-blank#6]
很喜欢这个主题~，安装好了过后，一些使用比如音乐播放器，新增搜索页面，标签页面没研究出来，使用提示的网页也挂了，麻烦作者弄一下帮助手册~

**Comment by dewjohn** [comment]
好的，尽快恢复文档。
不要关闭此issure，新的链接会发给你

**Comment by dewjohn** [comment]
> 很喜欢这个主题~，安装好了过后，一些使用比如音乐播放器，新增搜索页面，标签页面没研究出来，使用提示的网页也挂了，麻烦作者弄一下帮助手册~

新的地址：[dmx-pub.vercel.app](https://dmx-pub.vercel.app)

**Comment by HiNinoJay** [comment]
收到，谢谢～
